version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:4.1
    container_name: spotify-tracker-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: spotify_tracker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spotify-tracker-network

  # ML API (FastAPI + LightFM)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spotify-tracker-ml-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api:/app
      - /app/__pycache__
    networks:
      - spotify-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (Node.js + Express)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: spotify-tracker-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://admin:password@mongodb:27017/spotify_tracker?authSource=admin
      - MONGO_DB=spotify_tracker
      - CLIENT_ID=${CLIENT_ID}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URI=http://localhost:5173
      - ML_API_URL=http://api:8000
    depends_on:
      - mongodb
      - api
    networks:
      - spotify-tracker-network
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (React + Vite)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: spotify-tracker-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_ML_API_URL=http://localhost:8000
    networks:
      - spotify-tracker-network
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  spotify-tracker-network:
    driver: bridge

volumes:
  mongodb_data:
